In [42]:
import numpy

In [3]:
li = [1, 2, 3]
type(li)

list

In [6]:
a = numpy.array(li)
a

array([1, 2, 3])

### Transform nested list to 2D array

In [10]:
mylist = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
matrix = numpy.array(mylist)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
matrix.shape

(3, 3)

## Numpy built in methods

In [15]:
numpy.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
numpy.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
numpy.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
numpy.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Broadcasting operations to every value in matrices

In [22]:
numpy.ones((4, 6)) + 6

array([[7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.]])

In [23]:
numpy.ones(10) * 100

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])

In [24]:
numpy.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [26]:
numpy.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### `numpy.random.rand`
creates random samples of uniform distribution between 0 and 1 (every values between 0 and 1 has the sam probability of getting chosen)

In [45]:
numpy.random.rand(3)

array([0.1578506 , 0.40306285, 0.57187145])

### `numpy.random.randn`
creates samples from the standard normal distribution (mean = 0, stdev = 1).

In [46]:
numpy.random.randn(10)

array([ 0.83856206,  0.84449059, -2.26963676, -1.47726399,  0.31750898,
        0.36295761,  0.16585161,  0.17356538, -0.09307324,  1.81978381])

### `numpy.random.randint`

In [74]:
numpy.random.randint(1, 100)

91

### `numpy.reshape`

In [79]:
a = numpy.arange(25)
a.shape

(25,)

In [81]:
reshaped = a.reshape(5, 5)
reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### `numpy.min()` & `numpy.max()`

a = numpy.random.randint(0, 50, 10)
print(a)
print(a.min())
print(a.max())

### `numpy.argmin()` & `np.argmax()`

In [94]:
print(a.argmin())
print(a.argmax())

7
5


### `numpy.dtype`

In [95]:
a.dtype

dtype('int32')

## Selections and indexing

In [99]:
a = numpy.random.randint(0, 11, 10)
a

array([ 0,  6,  2,  8,  7, 10,  7,  9,  3,  8])

In [100]:
a[4]

7

### slicing 1D array

In [106]:
a[1:6]

array([ 6,  2,  8,  7, 10])

In [107]:
a[:5]

array([0, 6, 2, 8, 7])

In [108]:
a[5:]

array([10,  7,  9,  3,  8])

## Indexing 2D array

In [111]:
a_2s = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a_2s

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [112]:
a_2s[0]

array([1, 2, 3])