### 1. Import NumPy as np

In [27]:
import numpy as np

### 2. Create an array from this list

In [28]:
mylist = [9, 8, 7, 6, 5, 4, 3, 2, 1]
a = np.array(mylist)
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

### 3. Reshape the array you just created to the shape 3x3

In [29]:
new_a = a.reshape((3, 3))

### 4. Print the shape of the array you just  reshaped

In [30]:
new_a.shape

(3, 3)

### 5. Create an array of 25 fives with the shape of 5x5

In [31]:
zeros = np.zeros((5, 5))
fives = zeros + 5
fives

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

### 6. Create an array of 10 random numbers between 0 and 1

In [32]:
rand_a = np.random.rand(10)
rand_a

array([0.64031487, 0.14010954, 0.39570727, 0.03363427, 0.56657568,
       0.80671275, 0.75912169, 0.02537611, 0.37746332, 0.10913984])

### 7. Create a 10x10 matrix of random integers between 0 and 255 

In [33]:
matrix = np.random.randint(low=0, high=255, size=(10, 10))
matrix

array([[204, 126, 124,  14,  22, 121,  58,  99, 174,  89],
       [143, 193,  45, 108,  36,  78, 173,  62, 133,  81],
       [228,  17, 117, 205,  74, 122,  63, 167,  47, 222],
       [207,   0, 161, 131,  69, 207, 131,   9,  74, 211],
       [ 42,  60, 188,  46, 201,  21, 213, 230, 144,   4],
       [247, 118, 235,  71, 212,  52, 111,  92,  63,  68],
       [ 56,  14,   7, 160,  18, 239, 250,  82, 141,  49],
       [160, 229,  61,  72, 206,  23,  24, 229, 119, 113],
       [ 12, 137, 183, 138, 103,  83,  82,  13,   1, 250],
       [152, 252,  34, 233, 194, 132, 218, 239, 204,  81]])

### 8. Based on your previous matrix, get the item which is in row 6 and column 4

In [34]:
matrix[5][3]

71

### 9. Based on your previous matrix, select the last value from every row

In [35]:
matrix[:, -1]

array([ 89,  81, 222, 211,   4,  68,  49, 113, 250,  81])